backend:
  image:
    repository: swinalwaghmare/pingboard-backend
    tag: latest
  replicas: 2
  port: 8080
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: swinalwaghmare/pingboard-frontend
    tag: latest
  replicas: 2
  port: 80
  service:
    type: ClusterIP
    port: 80 
  wsBackendUrl: "ws://backend-service:8080/ws/chat"

deployment:
  slot: blue
  