pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        BACKEND_IMAGE = "swinalwaghmare/pingboard-backend"
        FRONTEND_IMAGE = "swinalwaghmare/pingboard-frontend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test Backend') {
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                dir('backend') {
                    sh '''
                        pip install  -r  requirements.txt
                        pip install pytest httpx
                        pytest tests/ -v || echo "No tests found"
                    '''
                }
            }
        }

        stage('Build Images') {
            steps {
                sh "docker build -t ${BACKEND_IMAGE}:${IMAGE_TAG} ./backend"
                sh "docker build -t ${FRONTEND_IMAGE}:${IMAGE_TAG} ./frontend"
            }
        }

        stage('Push to Docker Hub'){
            when {
                anyOf {
                    branch 'main'
                    branch 'staging'
                }
            }
            steps {
                sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                sh "docker push ${BACKEND_IMAGE}:${IMAGE_TAG}"
                sh "docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}"
            }
        }

        stage('Deploy to Staging') {
            when {
                    branch 'staging'
                }
            steps {
                withCredentials([string(credentialsId: 'kubeconfig-eks', variable: 'KUBECONFIG_DATA')]) {
                    sh '''
                        echo "$KUBECONFIG_DATA" | base64 -d > /tmp/kubeconfig
                        export KUBECONFIG=/tmp/kubeconfig
                        helm upgrade --install pingboard-staging ./helm/pingboard \
                            --set backend.image.tag=${IMAGE_TAG} \
                            --set frontend.image.tag=${IMAGE_TAG} \
                            --set deployment.slot=blue \
                            --namespace staging --create-namespace
                        rm /tmp/kubeconfig
                    '''
                }
            
            }
        }


        stage('Deploy to Production') {
            when {
                branch 'main'
            }
            steps {
                withCredentials([string(credentialsId: 'kubeconfig-eks', variable: 'KUBECONFIG_DATA')]) {
                    sh '''
                        echo "$KUBECONFIG_DATA" | base64 -d > /tmp/kubeconfig
                        export KUBECONFIG=/tmp/kubeconfig
                        helm upgrade --install pingboard-prod ./helm/pingboard \
                            --set backend.image.tag=${IMAGE_TAG} \
                            --set frontend.image.tag=${IMAGE_TAG} \
                            --set deployment.slot=blue \
                            --namespace production --create-namespace
                        rm /tmp/kubeconfig
                    '''
                }
            }
        }

    post {
        success {
            echo "Pipeline succeeded — build ${BUILD_NUMBER}"
        }
        failure {
            echo "Pipeline failed — check logs above"
        }
    }

}

}