apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: pingboard-frontend
    slot: {{ .Values.deployment.slot }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.frontend.service.type }}